sonar.projectKey=NexusBank
sonar.projectName=NexusBank
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.issue.ignore.multicriteria=cx
sonar.issue.ignore.multicriteria.cx.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.cx.resourceKey=src/index.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
